name: Deploy master branch

on:
  push:
    branches:
      - master

jobs:
  deploy:
    - name: Set up Node
      uses: actions/setup-node@v1
      with:
        node-version: 12

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Serverless Deploy
      uses: dhollerbach/github-action-serverless-with-python-requirements@master
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}